### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by tucotuco** [kurator-org/kurator-validation#6]
Trying to count the values of stateprovince from an input file in utf8 that contains non-ascii characters throws an exception.

$ python term_value_count_reporter.py -w ./workspace -i ./data/vocabularies/country.txt -o testtermcountout.txt -t "country" -s "|" -f txt
optdict: {'termlist': ['country'], 'outputfile': 'testtermcountout.txt', 'format': 'txt', 'loglevel': None, 'separator': '|', 'workspace': './workspace', 'inputfile': './data/vocabularies/country.txt'}
Traceback (most recent call last):
  File "term_value_count_reporter.py", line 280, in <module>
    main()
  File "term_value_count_reporter.py", line 276, in main
    response=term_value_count_reporter(optdict)
  File "term_value_count_reporter.py", line 154, in term_value_count_reporter
    success = term_value_count_report(outputfile, counts, termname=termname, format=format)
  File "term_value_count_reporter.py", line 202, in term_value_count_report
    writer.writerow({termname:item[0].encode('utf-8'), 'count':item[1] })
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)

**Comment by tucotuco** [comment]
Fixed by importing the unicodecsv package in commit fffd43240ae82bd009931fab7c1c040499744739.
